name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install `bun`
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run compile

      - name: Upload JavaScript .map files for symbols
        uses: actions/upload-artifact@v4
        with:
          name: debug-vscode-tikbook-maps
          path: |
            *.map
            ./out/*
            ./**/out/*
            **/*.bun-build

      - name: Package VSIX
        run: |
          npm run vsix:package

      - name: Upload VSIX artifact (node)
        uses: actions/upload-artifact@v4
        with:
          name: tikbook-node.vsix
          path: tikbook-node.vsix

      - name: Upload VSIX artifact (web)
        uses: actions/upload-artifact@v4
        with:
          name: tikbook-web.vsix
          path: tikbook-web.vsix

      - name: Get package version
        id: pkgver
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: v${{ steps.pkgver.outputs.version }}
          tag: v${{ steps.pkgver.outputs.version }}
          draft: false
          prerelease: true
          allowUpdates: true
          updateOnlyUnreleased: true
          body: |
            **TikBook for RouterOS** (v${{steps.pkgver.outputs.version}})

            > [!NOTE]
            >
            > "Known Issues" and "Changelog" can be found in [CHANGES.md](https://github.com/tikoci/vscode-tikbook/blob/main/CHANGES.md).
            >
            > See [README.md](https://github.com/tikoci/vscode-tikbook/README.md) for more details about installation and usage.
            >

            Download `tikbook-node.vsix` and install use `code --install-extension tikbook-node.vsix` from your download directory.

          artifacts: |
            tikbook-web.vsix
            tikbook-node.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # TODO: Publish release should be it's own build task, VSCode works and Open-VSX should too
      #
      - name: Publish to VSCode Marketplace (node)
        run: npx @vscode/vsce publish --packagePath ./tikbook-node.vsix --no-dependencies --pre-release -p ${{secrets.VSCE_PAT}}
      - name: Publish to VSCode Marketplace (web)
        run: npx @vscode/vsce publish --packagePath ./tikbook-web.vsix --no-dependencies --target web --pre-release -p ${{secrets.VSCE_PAT}}
      - name: Publish to Open-VSX too
        run: npx ovsx publish tikbook-node.vsix -p ${{secrets.OVSX_PAT}}
